### ISSUE TITLE
A note to John

### ISSUE THREAD

**Issue by nihal2day** [smcAdvJavaGrp2/MealGuru#3]
Hey John, 

I have been working this morning with Jason and Theda in trying to get the Guru GUI to work, and we are still not done getting it to work, but will keep working on it.

In traversing the program, there are a few issues I have found - some which you may be aware of already, but I thought I would share: 

1. The button that you click to go into the page that allows you to put a meal together has no title so the user may be confused as to what that button even does
2. The phone number textbox allows letters to be entered and it also puts in my number in reverse
3. MealName does not edit
4. Not an issues but a suggestion: instead of having a drop down for Local/USDA database search, We could just search both databases at once which may be more userfriendly.

Happy to work on either the above or the below things which we have identified still need to be done.'

1. GUI Genie (in progress)
2. Data analysis via chart

Let us know!

**Comment by jscul** [comment]
Thanks for working on that today.

The button can be changed fairly easily. That's a graphical design question - I'm not the most aesthetic guy but would you prefer the lettering to be above the image or just to the side. If we do it just to the side the only thing we really have to change is _new Button();_ to _new Button("New Meal");_

The phone number text field I'm working on. I've been experimenting with ways to make that work. If you want to take a crack at it, by all means go for it.

The MealEditor GUI doesn't really do anything at the moment. I'm working on the interface tomorrow with Liz and Jo.

We could have them search through both at the same time. I included the preference so that if someone created their own variation of a food they'd be able to find it more easily.

If you take a look at the DailyIntakeGraph, that's where all the graph stuff is...
